name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Docker image (smoke)
        run: |
          docker build -t acquisitions:ci .
      
      - name: Smoke test start/stop
        env:
          PORT: 3000
          NODE_ENV: test
        run: |
          docker run -d --rm -p 3000:3000 --name acquisitions-ci \
            -e NODE_ENV=test \
            -e PORT=3000 \
            -e DISABLE_SECURITY=true \
            -e ARCJET_KEY=dummy-ci-key \
            acquisitions:ci
          # Esperar a que arranque
          for i in {1..20}; do
            if curl -sf http://localhost:3000/health > /dev/null; then
              echo "Healthcheck OK"; break; fi; sleep 1; done
          curl -sf http://localhost:3000/health
          docker stop acquisitions-ci
